"""remove short_name should be unique

Revision ID: 05efa2727fbd
Revises: 7870f46c2141
Create Date: 2023-01-08 19:09:42.118559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05efa2727fbd'
down_revision = '7870f46c2141'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('drivers_short_name_key', 'drivers', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('drivers_short_name_key', 'drivers', ['short_name'])
    # ### end Alembic commands ###
