"""Make is_superuser column required

Revision ID: 416e700988c0
Revises: ec35214843f5
Create Date: 2023-01-02 18:00:18.634997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '416e700988c0'
down_revision = 'ec35214843f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
