"""Make short_name unique

Revision ID: 7870f46c2141
Revises: 6e186910b925
Create Date: 2023-01-07 01:20:01.859944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7870f46c2141'
down_revision = '6e186910b925'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
